apiVersion: v1
kind: ConfigMap
metadata:
  name: messaging-app-config
  namespace: messaging-app
data:
  config.yaml: |
    database:
      dsn: host=pgbouncer user=postgres password=postgres dbname=messages port=6432 sslmode=disable
    redis:
      addr: redis:6379
    webhookurl: http://wiremock:8080/webhook
    scheduler:
      batchsize: 2
      interval: 2m
      enabled: true
      maxconcurrent: 2
      maxretryconcurrent: 1
    server:
      port: 8080